site_name: Fictions
site_url: https://romain.sertelon.fr/fictions/
site_description: 'Fictions écrites par Romain Sertelon'
site_author: 'Romain Sertelon'

nav:
  - Accueil: 'index.md'
  - Zernod: 'zernod/journal.md'
  - Malrik Faërulea: 'malrik/journal.md'

theme:
  name: readthedocs
  include_homepage_in_sidebar: false
  prev_next_buttons_location: 'none'

docs_dir: 'fictions'

use_directory_urls: false
